In [23]:
import numpy as np

# Generate marks of 10 students × 5 subjects
marks = np.random.randint(30, 101, (10, 5))

print("Student Marks:")
print(marks)

# Total marks of each student
total = marks.sum(axis=1)
print("\nTotal Marks:")
print(total)

# Average marks of each student
average = marks.mean(axis=1)
print("\nAverage Marks:")
print(average)

# Highest and Lowest scorer
highest = np.argmax(total)
lowest = np.argmin(total)

print("\nHighest Scoring Student Index:", highest)
print("Marks:", marks[highest])

print("\nLowest Scoring Student Index:", lowest)
print("Marks:", marks[lowest])

# Overall class statistics
print("\nOverall Class Mean:", marks.mean())
print("Overall Class Standard Deviation:", marks.std())

# Top 3 students
top3 = np.argsort(total)[-3:][::-1]

print("\nTop 3 Student Indices:", top3)
print("Marks of Top 3 Students:")
print(marks[top3])

Student Marks:
[[ 91  86  60  79  46]
 [ 61  34  89  80  43]
 [ 59  43  57  74  56]
 [ 51 100  63  54  95]
 [ 91  84  74  45  61]
 [ 52  33  58  65  34]
 [ 72  68  46  40  37]
 [ 36  80  69  97  57]
 [ 46  49  42  67  32]
 [ 36  35  80  86  53]]

Total Marks:
[362 307 289 363 355 242 263 339 236 290]

Average Marks:
[72.4 61.4 57.8 72.6 71.  48.4 52.6 67.8 47.2 58. ]

Highest Scoring Student Index: 3
Marks: [ 51 100  63  54  95]

Lowest Scoring Student Index: 8
Marks: [46 49 42 67 32]

Overall Class Mean: 60.92
Overall Class Standard Deviation: 19.41426279826252

Top 3 Student Indices: [3 0 4]
Marks of Top 3 Students:
[[ 51 100  63  54  95]
 [ 91  86  60  79  46]
 [ 91  84  74  45  61]]
