In [13]:
import numpy as np

arr = np.random.randint(10, 101, (5, 6))

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array:
 [[ 64  15  18  98  99  60]
 [ 46  60  49  52  72  58]
 [ 64  22  90  38  70  45]
 [ 45  91  87 100  78  46]
 [ 31  72  33  35  16  86]]
Shape: (5, 6)
Size: 30
Data Type: int64
