In [16]:
import numpy as np

matrix = np.random.randint(20, 81, (4, 5))

print(matrix)
print("Minimum:", matrix.min())
print("Maximum:", matrix.max())
print("Sum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())

print("Row Sum:", matrix.sum(axis=1))
print("Column Sum:", matrix.sum(axis=0))

[[65 57 56 32 58]
 [52 43 23 45 51]
 [68 33 33 46 68]
 [35 38 43 72 77]]
Minimum: 23
Maximum: 77
Sum: 995
Mean: 49.75
Standard Deviation: 14.794847075924778
Row Sum: [268 214 248 265]
Column Sum: [220 171 155 195 254]
