In [17]:
import numpy as np

arr = np.arange(1, 25)

a = arr.reshape(4, 6)
b = arr.reshape(3, 8)
c = arr.reshape(2, 3, 4)

print(a)
print("Shape:", a.shape)

print(b)
print("Shape:", b.shape)

print(c)
print("Shape:", c.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
