In [18]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Original Array:\n", arr)

# First row
print("First Row:")
print(arr[0])

# Last column
print("Last Column:")
print(arr[:, -1])

# Center 2x2 submatrix
print("Center 2x2 Submatrix:")
print(arr[1:3, 1:3])

# Even numbers using Boolean Indexing
print("Even Numbers:")
print(arr[arr % 2 == 0])

Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First Row:
[10 20 30 40]
Last Column:
[ 40  80 120]
Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]
Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]
