In [19]:
import numpy as np

arr = np.random.randint(1, 101, (5, 5))

print("Original Array:\n", arr)

# Diagonal elements
print("Diagonal Elements:")
print(np.diag(arr))

# Elements greater than 50
print("Elements Greater Than 50:")
print(arr[arr > 50])

# Replace elements less than 30 with 0
arr[arr < 30] = 0

print("Modified Array:")
print(arr)

Original Array:
 [[ 72  10  68  68  60]
 [100  31  23  90  53]
 [ 62  98  13   1  90]
 [ 14  20  39  66  18]
 [ 35  50  95  31  68]]
Diagonal Elements:
[72 31 13 66 68]
Elements Greater Than 50:
[ 72  68  68  60 100  90  53  62  98  90  66  95  68]
Modified Array:
[[ 72   0  68  68  60]
 [100  31   0  90  53]
 [ 62  98   0   0  90]
 [  0   0  39  66   0]
 [ 35  50  95  31  68]]
