In [21]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

# Element-wise multiplication
print("Element-wise Multiplication:")
print(A * B)

# Matrix multiplication
print("Matrix Multiplication:")
print(A @ B)

# Difference:
# * → Element-wise multiplication
# @ → Matrix multiplication

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
