In [22]:
import numpy as np

arr = np.random.randn(6, 6)

print(arr)

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

print("Maximum Index:", np.unravel_index(np.argmax(arr), arr.shape))
print("Minimum Index:", np.unravel_index(np.argmin(arr), arr.shape))

print("Top-left 3x3 Matrix:")
print(arr[:3, :3])

# Convert negative values to positive
arr[arr < 0] = np.abs(arr[arr < 0])

print("Modified Matrix:")
print(arr)

print("Mean:", arr.mean())

[[-0.81880231  0.02223194  0.44122916  0.82356939  0.36504958  0.68071481]
 [-0.08588324  0.74398281  0.03363474 -0.79812599 -0.11118978 -1.00569414]
 [-0.62976623 -0.22509105  1.10874921 -0.06167891 -0.9592817   0.77733597]
 [-0.65441876 -1.54532891  0.71621639  0.17846154 -1.44356789  0.54026569]
 [-2.0808762  -1.10704305 -0.21486443  1.18932965 -0.75592976  0.50308197]
 [-0.94373478 -0.44277145 -0.23731112 -0.90968794 -0.15929632 -0.68108504]]
Shape: (6, 6)
Size: 36
Data Type: float64
Maximum Index: (np.int64(4), np.int64(3))
Minimum Index: (np.int64(4), np.int64(0))
Top-left 3x3 Matrix:
[[-0.81880231  0.02223194  0.44122916]
 [-0.08588324  0.74398281  0.03363474]
 [-0.62976623 -0.22509105  1.10874921]]
Modified Matrix:
[[0.81880231 0.02223194 0.44122916 0.82356939 0.36504958 0.68071481]
 [0.08588324 0.74398281 0.03363474 0.79812599 0.11118978 1.00569414]
 [0.62976623 0.22509105 1.10874921 0.06167891 0.9592817  0.77733597]
 [0.65441876 1.54532891 0.71621639 0.17846154 1.44356789 0.5