In [5]:
import numpy as np

a = np.random.rand(10)

b = np.random.randn(3,3)

c = np.random.randint(10,51,(4,5))

print("Random Numbers")
print(a)

print("\nStandard Normal Matrix")
print(b)

print("\nRandom Integer Matrix")
print(c)

Random Numbers
[0.99999979 0.81526454 0.51983543 0.43023011 0.20095501 0.91424897
 0.97885341 0.7590293  0.03649358 0.41814427]

Standard Normal Matrix
[[-1.13576463  1.27876215 -0.39813325]
 [ 0.92144688  1.71096053  0.94522064]
 [-0.15033377  0.10985327 -0.07233777]]

Random Integer Matrix
[[43 48 38 37 21]
 [16 33 24 17 26]
 [19 16 24 46 18]
 [33 50 23 28 39]]
