In [2]:
import numpy as np

a = np.zeros(8)
b = np.ones((4,4))
c = np.zeros((3,3))

print("1D Array of Zeros")
print(a)

print("\n4x4 Ones Matrix")
print(b)

print("\n3x3 Zero Matrix")
print(c)

1D Array of Zeros
[0. 0. 0. 0. 0. 0. 0. 0.]

4x4 Ones Matrix
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Zero Matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
