In [8]:
import numpy as np

A = np.random.randint(1,101,(4,4))

print(A)

print("Shape:",A.shape)
print("Dimension:",A.ndim)
print("Size:",A.size)
print("Data Type:",A.dtype)
print("Minimum:",A.min())
print("Maximum:",A.max())

[[68 40 82 14]
 [67 55 52 64]
 [29 30 71 35]
 [ 1 18 84  4]]
Shape: (4, 4)
Dimension: 2
Size: 16
Data Type: int64
Minimum: 1
Maximum: 84
