In [6]:
import numpy as np

v1 = np.array([2,4,6,8])
v2 = np.array([1,3,5,7])

print("Addition")
print(v1+v2)

print("Subtraction")
print(v1-v2)

print("Element-wise Multiplication")
print(v1*v2)

print("Dot Product")
print(np.dot(v1,v2))

Addition
[ 3  7 11 15]
Subtraction
[1 1 1 1]
Element-wise Multiplication
[ 2 12 30 56]
Dot Product
100
