In [9]:
import numpy as np

arr = np.random.randint(1,51,20)

matrix = arr.reshape(4,5)

print(matrix)

print("Sum =", matrix.sum())
print("Mean =", matrix.mean())
print("Standard Deviation =", matrix.std())

print("Maximum in each row")
print(matrix.max(axis=1))

[[45 48 43 43  5]
 [ 8  8  1  1  4]
 [38 26 34 35 32]
 [30 49 30  1 26]]
Sum = 507
Mean = 25.35
Standard Deviation = 16.95368691465075
Maximum in each row
[48  8 38 49]
