In [10]:
import numpy as np

try:
    n = int(input("Enter number of random values: "))

    arr = np.random.randint(10,101,n)

    print("\nGenerated Array")
    print(arr)

    print("\nMean =", np.mean(arr))
    print("Median =", np.median(arr))
    print("Standard Deviation =", np.std(arr))
    print("Minimum =", np.min(arr))
    print("Maximum =", np.max(arr))

    if n % 2 == 0:
        matrix = arr.reshape(2, n//2)

        print("\nReshaped Matrix")
        print(matrix)

        print("\nRow-wise Sum")
        print(np.sum(matrix, axis=1))

    else:
        print("\nCannot reshape into a 2D array with 2 rows because the number of elements is odd.")

except ValueError:
    print("Please enter a valid integer.")

Enter number of random values: 10

Generated Array
[97 64 80 85 19 10 39 63 41 78]

Mean = 57.6
Median = 63.5
Standard Deviation = 27.69187606501228
Minimum = 10
Maximum = 97

Reshaped Matrix
[[97 64 80 85 19]
 [10 39 63 41 78]]

Row-wise Sum
[345 231]
